name = "mattus mods"
author = "Mattu"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be1234c80ccb5c6506a23cd8482c79dd373b969dd5f14385bf85c44eb39b3f74"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
