name = "mattus mods"
author = "Mattu"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f62a0b5fc0016c8ec18cdf833724bb90ee10ce2978083543e7cb376e9d6fba3"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
